### ISSUE TITLE
project impact : prize

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#1035]
One of our LAs recently received a prize related to work in our projects.
Adding this as 'other' feels a bit too little for such a nice achievement.

Can you add a 'Prize' category-type for project (and software) impact?

**Comment by ewan-escience** [comment]
Related to #757.

**Comment by jiskattema** [comment]
ah, i see. then close this one.

**Comment by bakhshir** [comment]
I would like to :+1:  to this feature request for projects. One of our colleagues got best paper award :1st_place_medal: and now we awkwardly put it on the page, citing an article that we wrote (because this feature does not exist for RSD): 

https://research-software-directory.org/projects/searchseco
