### ISSUE TITLE
Pagination counts pages of results

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#1098]
On the software and projects overview, the pagination counter counts:

`Page <page number> of <total software/project entries>`

This information relates numbers of different entities (pages vs. total entries) to each other which do not correlate. As a visitor I would expect that when I navigate to the last page, both numbers are the same.

Here is an example of the last page in the software overview:

![image](https://github.com/research-software-directory/RSD-as-a-service/assets/14222414/7ad70d0c-3675-4d50-b564-e8e3ab9086d2)

I propose that the page counter could behave like one of the following examples:

- `Page <page number> of <total pages> for <total entries> entries`
- `Page <page number> of <total pages>`
- `Page <page number>`

**Comment by jmaassen** [comment]
Indeed, the current approach mixes two units which is weird. The two bottom suggestions make the most sense to me, but if we go for either of those we lose the total result counter? I don't think its somewhere else on the page.

**Comment by dmijatovic** [comment]
We have another approach on the [organisation overview page](https://research-software-directory.org/organisations), where we use count-range instead of page count (see image or link)?

![image](https://github.com/research-software-directory/RSD-as-a-service/assets/9204081/bc612e9b-e026-444e-affe-cb510426df1f)
