### ISSUE TITLE
What is the % of Code Coverage in this code repo?

### ISSUE THREAD

**Issue by priya-gitTest** [research-software-directory/RSD-as-a-service#1159]
What is the % of Code Coverage in this code repo?

**Comment by priya-gitTest** [comment]
Something like this ... 
![image](https://github.com/research-software-directory/RSD-as-a-service/assets/21082240/29793d9b-46b1-41e1-b327-982b8b23bd6f)

**Comment by ewan-escience** [comment]
Thanks for your suggestion. We are currently busy with other things, but will have a look when we have more time. Note that this is also complicated on a technical level, since we have different modules that get evaluated by SonarCloud independently. We might decide to add a separate badge on every module.
