### ISSUE TITLE
upgrade tailwindcss package

### ISSUE THREAD

**Issue by fembau** [research-software-directory/RSD-as-a-service#1217]
I'm currently working on the table representation of category hierarchies (#992) and I'm facing an incorrect rendering when using tailwinds [subgrid](https://tailwindcss.com/docs/grid-template-columns#subgrid): Cells inside the subgrid are rendered vertically instead of horizontally. I tried tailwindcss v3.4.3 and it is fixed there.

**Comment by dmijatovic** [comment]
I expect no problems to bump version to v3.4.3. We are now using 3.3.2. Maybe also see if `@tailwindcss/typography` can be also bumped to the latest version `0.5.13`.

Because you need the functionality right now, please go ahead and bump the versions in your branch and mention it in your PR. Is this approach OK with you?
