### ISSUE TITLE
Add views counter to the software pages

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#290]
in Zenodo, you can see this counter as well for each publication
image
![image](https://user-images.githubusercontent.com/4195550/170204875-16cd1941-7a72-46c6-8e45-d50b7e70f588.png)

It will be nice to have the number of visits and maybe downloads? to the page

when clicking on see more details this is the view:
![image](https://user-images.githubusercontent.com/4195550/170204895-bbde9851-4f8e-4316-aaf9-06fa4fd63b8b.png)

**Comment by jmaassen** [comment]
Could we use information from Matomo fot this?

**Comment by ewan-escience** [comment]
We have decided not to do this, mainly because the added value is not high. Scientific output and impact are more important, as well as impact measures on GitHub (stars, clones).

Furthermore, it is hard to do this technically. Some people block Matomo, and not every instance of the RSD necessarily uses Matomo. So you'd have to to this in the RSD itself, where you have to take into account duplicate views, bots... And we're already running for some years in which we have not tracked views.
