### ISSUE TITLE
Research how to extract information from GitLab

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#32]
Let's see what are the requirements, and write some thoughts about them.

**Comment by ewan-escience** [comment]
### GitHub
Rate limit is 5000 requests per hour for authenticated users. For users that belong to a GitHub Enterprise Cloud account, it is 15000 requests per hour.

### GitLab
On GitLab.com there is a table here: https://docs.gitlab.com/ee/user/gitlab_com/index.html#gitlabcom-specific-rate-limits but could be up to 2000 requests per minute for authenticated users. For self hosted instanced, it depends on the settings.

**Comment by jmaassen** [comment]
Done in PR #99

**Comment by jmaassen** [comment]
Oops. This was gtilab, not github.

**Comment by ewan-escience** [comment]
A call to [here](https://gitlab.com/gitlab-org/gitlab-foss/-/graphs/master?format=json) could be used instead. It's limited to 6000 commits, though. If you omit `?format=json` you can see the graphical version. I don't think it's part of the official API though. 

I'm fine with your last suggestion, but for GitLab only. (I prefer to scrape the whole history when possible, as the history could change.) We could use the existing `commit_history_scraped_at` column to only scrape the latest commits. 

For the programming languages, in the frontend, the lines of code are converted to percentages, so that should not be a problem.

**Comment by ewan-escience** [comment]
This was implemented in #217.
