### ISSUE TITLE
"File is too large" warning stays open on all pages when not being closed manually

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#337]
While testing #331, I found that the warning that appears when trying to upload an image in the project settings with > 2MB will stay open unless being closed manually. The message will stay open when changing the page, e.g. going back to the landing page.

/cc @dmijatovic

**Comment by dmijatovic** [comment]
@cmeessen That is intentional behavior for error (snackbar) message. Info and success message type will disappear after (X) seconds, but error the user should close it manually in order to ensure the user sees error message (some error message might need some time by user to process/understand the message).

**Comment by dmijatovic** [comment]
@cmeessen In this specific case, I will actually change the message to warning type, as this looks to me not a catastrophic failure, so it will remove itself after (X) seconds
