### ISSUE TITLE
RSD is not in eScience Center housestyle

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#387]
The RSD is not using our Housestyle.

**Comment by jmaassen** [comment]
Indeed it is not, and it never will as the RSD is used by 5 different organizations at the moment. Using the eScience Center housestyle will severly limit the uptake.

**Comment by jiskattema** [comment]
But it should. If it is to replace projects on our corporate website, it needs our housestyle. Or have joris/communication explicitly tell me it doesn't.

**Comment by jmaassen** [comment]
Nope. The purpose of the RSD is to offer a directory to all research institutes in the Netherlands, and various international partners. By now the eScience Center itself is actually becoming one of the smallest players in this project (with Helmholtz, Utrecht University, Leiden University, Amsterdam UMC, and interest from ODISSEI, STFC, ...). Forcing the eScience Center housestyle on all of them does not make sense, that's why it was decided to have a more neutral style instead.

This is not a problem, as we extensively use things like github, office365, etc., none of which are in our house style. Many of the public web pages we build are not in our house style either (take via appia for example). 

We are planning to offer a REST API (and maybe a wordpress plugin?) to allow the 'export' of data to other systems. This may a way to include the data on the esciencecenter.nl site and in the house style?

**Comment by jmaassen** [comment]
After further discussion within the eScience Center (with Communications, SHs, and PMs present), the conclusion was to go for a solution where the corporate site (wordpress) can extract the info it needs from the RSD using a REST API. See #483
