### ISSUE TITLE
Implement cookie notification

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/RSD-as-a-service#392]
A quick look shows that the website places 2 cookies; however, there is no cookie notification or banner.
Given that the cookies are purely functional, permission to store is probably not necessary. However, showing a message that we use functional cookies only, and nothing else (ie. google analytics..?) could be useful.

**Comment by jmaassen** [comment]
Good suggestion, we'll look into this

**Comment by jmaassen** [comment]
We may have to check with legal what the rules are on this?

**Comment by cmeessen** [comment]
Since with #435 we integrated support for Matomo, we would also need a cookie notification banner where the user has the choice to accept or decline tracking. Ideally, based on the environemnt variables, the banner would automatically detect what to show.

In case of Matomo, or other tracking tools, there also needs to be the option to withdraw the consent elswhere. This could either be done on a dedicated privacy policy page (with more custom text), or on a dedicated "Cookie settings" page that might be referenced in the footer. In my opinion, the cookie settings page would be more transparent and more easily accessible than the solution in the privacy policy page. On the other hand, this may potentially clutter the footer. Do you have an opinion here?

@ruester is currently implementing the consent banner (ready to be merged here soon), and we are now thinking about where to place the withdrawal-option.

**Comment by jmaassen** [comment]
Part of PR #488
