### ISSUE TITLE
Linking existing organisation with ROR id fails when ROR organisation was referenced elsewhere

### ISSUE THREAD

**Issue by cmeessen** [research-software-directory/RSD-as-a-service#457]
Steps to reproduce

1. Create an organisation without linking it to the ROR id
2. Create or edit a project, navigate to "Organisations"
3. Under "Add organisation", type the name of the organisation you just added (will list RSD and ROR entries)
4. Select the ROR entry
5. Navigate back to Organisations -> The one you created in the first step
6. open Organisation settings
7. click the refresh button next to the ROR id field
8. in the modal, select the corresponding organisation that you added in step 4
9. Error message will appear: `Failed to save. : duplicate key value violates unique constraint "organisation_ror_id_key"`

/edit: what is happening is that when referencing the organisation in step 4, it will create a new one. So you cannot link two organisations with the same ROR (which is correct). At this point it would be handy to have delete function as mentioned in #448

**Comment by bakhshir** [comment]
Yes, this is the same as #442

**Comment by ewan-escience** [comment]
This is in principle expected behaviour. With #537, we also expect that this won't happen much anymore, even more so since the admin interface doesn't allow you to create an organisation without linking it to software or a project first. 

It could be a problem when an organisation in the RSD db didn't have a ROR-id for a long time, and later does get one. We should allow for "merging" the two entries in the admin interface, but since this will be such a rare event, this is more for the long term.

**Comment by ewan-escience** [comment]
Now that admins can delete organisations since #1286, we consider this to be not an issue anymore.
