### ISSUE TITLE
Feedback UU: importing the (raw) readme

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#494]
As expected, importing the Readme.md from github gave some confusion. We may need to improve this a bit? Can be partially automate it maybe? Like an "import Readme.MD" from github/gitlab button?

**Comment by cmeessen** [comment]
Example from GitLab:

HTML view:

```
https://codebase.helmholtz.cloud/research-software-directory/RSD-as-a-service/-/blob/main/README.md?ref_type=heads
```

Raw view:

```
https://codebase.helmholtz.cloud/research-software-directory/RSD-as-a-service/-/raw/main/README.md?ref_type=heads
```

**Comment by dmijatovic** [comment]
I just did some initial testing with gitlab and found out that we cannot perform these requests from RSD due to CORS policy defined by Gitlab.

|provider|html|raw|localhost|remarks|
|------------|-------|-----|-------------|------------|
|Github|CORS error|OK|CORS errors|We can load raw README.md (different domain and CORS)|
|Gitlab|CORS error|CORS error|CORS error|Gitlab.com does not allow requests from RSD frontend|
|Bitbucket|OK|OK|OK|We can load raw README.md from RSD frontend|
|Other|?|?|?|

## Gitlab does not allows request from RSD domain
![image](https://github.com/user-attachments/assets/7e8280d9-2ebe-461e-8d1d-d287aa113c8c)
