### ISSUE TITLE
Feedback UU: save button

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#495]
To the users at UU it was confusing that when adding / editing data there sometimes is a save button, and sometimes not. Maybe we can be more consistent with this? I'd be fine to always have a "save"

**Comment by dmijatovic** [comment]
I think it would be more user friendly to remove Save button and save automatically on change. All edit software pages, except info page (first section) do not have Save button. The first page has Save button because quite a lot of input is present on the page, however it should be possible to enhance all these input sections and save automatically after something is changed. 

This is a larger feature I would like to investigate.
