### ISSUE TITLE
no way to edit existing keywords from the RSD UX?

### ISSUE THREAD

**Issue by bakhshir** [research-software-directory/RSD-as-a-service#499]
Say, I type in a keyword, all letters lower case and then change my mind, remove it and trying to type the same keyword with capitalized first letters, the interface would just give me back my original existing keyword. Once the keyword is added, there is no way to remove (from the list of possible keywords) or edit it (if you want to change how it is displayed).

Is there a way to edit the existing keywords (used by the project pages) via the RSD front end?

**Comment by jmaassen** [comment]
This is intentional. Since keywords are shared between all project and software pages, changing a keyword one place would change all of them. However, it does make sense to be able to manage keywords somehow, to fix typos for example. This would probably be part of the RSD admin role however. 

For now we can manually do this for you in the database, but maybe its good to discuss about a better solution?

**Comment by bakhshir** [comment]
I am wondering about how many typos users may introduce, and how many keywords would need to be removed.

Some adhoc ideas that come to mind: 

- let's say a particular keyword is not used by any page, can it be removed automatically? 
- can keywords be just capitalized (first letter), even if user typed all lowercase letters?

In the end, it probably depends on where and if these keywords will be used, e.g. for filtering projects/software.

**Comment by ewan-escience** [comment]
In #600, we implemented these suggestions, i.e., we capitalise the first letter of each word, and when a keyword is removed from a software page or project, we will try to delete it from the database (which only works if that keyword is not used anywhere else). Would that be sufficient for this issue?
