### ISSUE TITLE
Import of license from DOI does not always seem to work?

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#518]
I'm not sure it this problem is at our side or Zenodo / datacite, but when I want to use the concept DOI of Xenon to import the license, the RSD claims that that information is not available. However, when checking the metadata at Zenodo, the Apache license is part of the data. 

This is the concept DOI:

10.5281/zenodo.597993

**Comment by dmijatovic** [comment]
I have checked current import methode. It seems that we are using `rightsIdentifier` property to validate that license is not already imported or manually defined. Our expectation was that each license provided by DOI object should have `rightsIdentifier` property. Somehow, Xenon DOI does not provide it (see json extract). Therefore no license is imported.

```json
[
    {
        "rights": "Apache License 2.0",
        "rightsUri": "http://www.opensource.org/licenses/Apache-2.0"
    },
    {
        "rights": "Open Access",
        "rightsUri": "info:eu-repo/semantics/openAccess"
    }
]
```
Maybe because it is older DOI version and `rightsIdentifier` property did not existed at that time?
We can change our validation process to use license "name"/"label" instead of `rightsIdentifier`.
