### ISSUE TITLE
UU organization name dependency: duplicated entry?

### ISSUE THREAD

**Issue by bakhshir** [research-software-directory/RSD-as-a-service#531]
Weird issue: depending on how i try to add Utrecht University to participating organizations, RSD gives me different results. 

If I type University of Utrecht,
![Screenshot from 2022-09-20 10-58-22](https://user-images.githubusercontent.com/16703268/191215385-a90b8fde-6cb8-464a-bcda-e8053bf4f31c.png)

 this is what i get even if i choose proper ROR entry:
![Screenshot from 2022-09-20 10-47-08](https://user-images.githubusercontent.com/16703268/191214488-4e68ff6c-4a58-4b12-921a-af0c9eda4782.png)

If I type Utrecht University, I get the proper entry with the logo:
![Screenshot from 2022-09-20 10-47-25](https://user-images.githubusercontent.com/16703268/191214766-54002b6f-6d32-4a6d-934a-1168cd8a81dc.png)

**Comment by jmaassen** [comment]
The problem seems to be that the search in the RSD and ROR databases behave differently. The "University of Utrecht" doesn't seem to match the RSD entry, but ROR is smart enough to figure out that you actually mean "Utrecht University". 

We should improve the search, and ensure the RSD search is as least as smart as the ROR one

**Comment by jmaassen** [comment]
We have figured out a way to solve this issue. It basically comes down to this: 

- search in ROR first to get a list of potential hits
- search in RSD with both the string and the list of ROR-IDs the ROR search has returned
- return a de-duplicated list that prefers existing RSD entries over new ROR ones

We'll implement this an let you know when it's available.

**Comment by ewan-escience** [comment]
Isn't this the same as #442?

**Comment by bakhshir** [comment]
it does not give that error message.

**Comment by ewan-escience** [comment]
I do when I click on save, did you try that?

**Comment by ewan-escience** [comment]
I have to press save to get the same error as in #442. How do you trigger the error in #442? 

I think that in both cases, the RSD database doesn't find what you're looking for, but the ROR database does, because your search string doesn't match what's in the RSD db. But since the entry with the ROR *is* already in the RSD database, under a slightly different name, you will get an error when trying to add the suggestion from ROR db.
