### ISSUE TITLE
Technology POC with PostgREST, Posgres and Authorization

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#6]

**Comment by ewan-escience** [comment]
### Features of this POC
- Two simple tables, one for software, one for organisations.
- One many-to-many table between software and organisations.
- Two remote procedure calls (functions) that shows for a given organisation the list of software *not* related to the organisation and vice versa.
- The POC was registered at Azure so you can authenticate with a Microsoft account.
- The tables are protected with row level seurity. The following "business rules" were used: anyone can see the full content of all tables, logged in or not, and only logged in people with an email ending in "@esciencecenter.nl" can edit the tables.
- A frontend was created to support interacting with all the tables.

### Findings
- PostgREST 8.0.0 doesn't work with Postgres 14.0 due to a bug, see e.g. https://github.com/PostgREST/postgrest/issues/1857. It does work with Postgres 13.4.
- With PostgREST you get a lot out of the box, e.g. GET, PUT, POST, DELETE, PATCH endpoints for all tables and views, filtering, sorting, resoucre embedding (joins), validating JWT's... It allows for very quick development without needing to reinvent the wheel (while probably containing less bugs as well). Indeed, most time was spent on creating the frontend and creating the two custom functions in the database.
- All your endpoints will be very PostgREST specific. It will be near impossible to recreate all endpoints and query parameter combinations and if you ever decide to stop using PostgREST, your API clients might already depend on the existence of those endpoints.
- For now it seems that PostgREST provides all functionality we need. However, it is notoriously hard to predict future requirements. It might be the case that at some point PostgREST will hurt the project more tham help it.
- **Using PostgREST will impose the wrong mindset about applications, namely that an application is essentially a database where the backend and frontend are just details. This is wrong. An application is essentially the backend and the database (if any) and the frontend are just details.** <sub>Let the flamewar begin!</sub>

### Open questions
- How to prevent clients from setting the primary key themselves when inserting a new row?
- If a user has multiple roles, how to parse that in the database? 
- If organisations can be owned by other ogranisations and software in a sub-organisation should also be managed by the super-organisations, the admin permissions will form a directed, possibly cyclical graph. How to deal with that?
