### ISSUE TITLE
Name and surname missing in profile

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/RSD-as-a-service#607]
For the Interdisciplinary Physics Team organization, an ORCID login was used with a newly created ORCID (0000-0002-2731-9623) by @pitmonticone Unfortunately, this ORCID was initially set to share no information (not even a name). As a result, the profile now shows John Doe: 

![thumbnail_Screenshot 2022-10-25 at 18 02 29](https://user-images.githubusercontent.com/1705533/197957888-25843581-864c-4f3d-a524-40d52c996092.png)

While this is a good approach if someone does not wish to share their identity, it was done by accident in this case. 

Changing the ORCID afterward to share the name does not seem to change anything in the RSD. I guess the name is only retrieved at first login? Also, there is no way to manually change this after the fact.

Can we fix this in the database? Also, this issue may occur more often as we get more users, so we may want to think about a better long-term solution?

**Comment by ewan-escience** [comment]
Indeed, we only save the name when you login for the first time. We could, on the profile page, facilitate changing it, or we could save the name on every login. And since an account could have multiple login methods (in the future), we should consider choosing your name from one of the OpenID providers tied to your account and even choosing a custom name.

**Comment by dmijatovic** [comment]
I think most flexible would be to have `Display Name` be populated with the value we first obtained but let the user change it on the profile page (be editable).
