### ISSUE TITLE
Misidentification of thesis mention.

### ISSUE THREAD

**Issue by BSchilperoort** [research-software-directory/RSD-as-a-service#609]
I have added two theses as mentions to [my software](https://research-software-directory.org/software/dtscalibration/).

However, _only one of the two_ shows up as a thesis, despite both coming from the TU Delft repository.

Looking at the documents on the TUD repository, both have the exact same `Document type`: `doctoral thesis` tags.

![image](https://user-images.githubusercontent.com/12114825/198018923-26a060b4-fba5-460a-ad99-2902ef49de5a.png)

Links:
https://doi.org/10.4233%2Fuuid%3A92565bdb-cf5a-4110-abf3-1b4298720466
https://doi.org/10.4233%2Fuuid%3A6d18abba-a418-4870-ab19-c195364b654b

**Comment by ewan-escience** [comment]
This is because the metadata we receive from DataCite differs for those two DOI's, and we didn't account for one of the cases. We will adapt the scrapers to include this case. 

For future reference, go to https://api.datacite.org/graphql and fill in the following:
```
query {
  works(ids: ["10.4233/uuid:6d18abba-a418-4870-ab19-c195364b654b","10.4233/uuid:92565bdb-cf5a-4110-abf3-1b4298720466"]) {
    nodes {
      doi
      types {
        resourceType
        resourceTypeGeneral
      }
      version
      titles(first: 1) {
        title
      }
      publisher
      publicationYear
      creators {
        givenName
        familyName
      }
      contributors {
        givenName
        familyName
      }
    }
  }
}
```
Look at the values for `resourceType` and `resourceTypeGeneral` for both. In the scraper, we should map `"resourceTypeGeneral": "Dissertation"` to `thesis` in the database.

**Comment by ewan-escience** [comment]
We have been using [version 4.3 of the DataCite Schema](https://schema.datacite.org/meta/kernel-4.3/), whereas [version 4.4 has been released](https://schema.datacite.org/meta/kernel-4.4/). Version 4.4 includes `Dissertation` as a value for `resourceTypeGeneral`, including many more, see the PDF. We should adapt the scraper to include all these new values.
