### ISSUE TITLE
Login failed: ORCID not whitelisted

### ISSUE THREAD

**Issue by wetneb** [research-software-directory/RSD-as-a-service#665]
I tried to login to register a new software package. I used ORCID to do so, but could not login because RSD returned the following error:

![image](https://user-images.githubusercontent.com/309908/203271868-90e0628b-630f-4c17-bc01-46a14b159a4d.png)

**Comment by ewan-escience** [comment]
We just added you to the whitelist. If you need further help, see https://research-software-directory.github.io/documentation/ or send us an email. 

For future reference, if anybody else sees this issue and wants to be on the whitelist, please go to https://research-software-directory.org/#get-started instead of opening an issue here. 😀

**Comment by wetneb** [comment]
I think it would be worth making this process clear in the log in form, or in the error message.
A lot of web services can be just signed up to via SSO without an explicit action of the service maintainers - it would be useful to explain better why you need a whitelist in the first place.
