### ISSUE TITLE
Define core design tokens for v2 (discussion)

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#824]
We would like to change design in RSD in version 2. RSD v1 frontend counts >1100 files (lot of these are UI components).
In order to have v2 components in the same design "logic" it is necessary to define basic design tokens to be used in all components. This will ensure consistency throughout the application and increase reusability of components.

- **Buttons**: 
     - primary button  (default)
![image](https://user-images.githubusercontent.com/9204081/229795307-36152b14-45d7-40d7-bffb-f71ee93a3c89.png)
    - primary, secondary buttons in modals (see Modals section)
  
- **Info/Alert boxes**: box with icon, with or without title. Text and url links only.
![image](https://user-images.githubusercontent.com/9204081/229790778-08c3905b-1e3f-4096-9060-f277e9d32fe5.png)
![image](https://user-images.githubusercontent.com/9204081/229791019-e49c437e-5c2b-4c86-9920-17af6559de97.png)
![image](https://user-images.githubusercontent.com/9204081/229810540-0c156c6f-3867-4437-82f1-d12b0ee65cf5.png)

- **Search box / Autocomplete input**: current  search box component 
![image](https://user-images.githubusercontent.com/9204081/229789566-839b8100-5eaa-40da-8ab0-9e6d1f13e627.png)

- **Inputs** (text/number/date): current input version, title - open input - help text/error message underneath
![image](https://user-images.githubusercontent.com/9204081/229791627-aee62bd7-b5f1-4fd8-8533-5d9c3213b985.png)

- **Modals**: current modal approach, header with bottom border, navigation with top border. Full screen on "small screens" < 640px
![image](https://user-images.githubusercontent.com/9204081/229793788-426ac8e3-41eb-487c-8fb0-610a847f9775.png)

- **Rounded borders**: currently no rounded borders are used on buttons, panels etc. (or a minimal rounded border with size of 2px)

Related to design changes for #820 (see image)

![image](https://user-images.githubusercontent.com/9204081/229816714-4bfc593d-6643-47cc-a9ab-f2a9638aa42d.png)

**Comment by ctwhome** [comment]
We are (sort of) following the Material design guidelines. I suggest sticking to it and not recreating the whole library, which can be very much time-consuming. 

However, it would be nice to agree on a few assumptions. It is important to see what to use in each specific place, which the context will give the meaning. We should not fall off on the belief that a few UI components should be spread throughout the whole application, otherwise, changing a general component could change in places that are not in control, introducing usability problems.

I would suggest that:

1.  UI components, should be independent, f.e. they shouldn't call API requests or interact with the application state.
2.  The majority of the components and their variants are already defined in MUI, we shouldn't recreate them. 
3.  Do not atomize too much. It is incredibly difficult to name things. We shouldn't create components out of each UI element or wrapper. Using Tailwindcss classes should be sufficient to create a solid wrapper without the need to create a stand-alone component for it. 
4.  We should only create components when they are needed to be reused somewhere else. Even with that, we have to be careful to name them well and be sure they are generic enough and well-documented.
