### ISSUE TITLE
Import Organization description to Organizations table

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#895]
The new design of organizations includes the country and a one-liner description for each one. 
In this list: I have included the description for 368 organizations, which should be more than enough to start with. 

We need to add the columns of "country", "lat" and "long" to the "Organisation" table and import the data.
<img width="377" alt="image" src="https://github.com/research-software-directory/RSD-as-a-service/assets/4195550/189b9de1-90c0-4028-98d0-5a6d1feb8eec">

**Comment by ewan-escience** [comment]
is the one line description going to be different from the existing `description` field, aka, do we need to add another field called `short_description`? Because the `description` field can use Markdown.

**Comment by ctwhome** [comment]
In any case it will be different from the about page, which I don't know what field is using in the database

**Comment by ewan-escience** [comment]
In that case it should be a new field, since the about part uses the `description` field. 

I did the database and data generation part in the branch `895-extra-organisation-fields` (see also [here](https://github.com/research-software-directory/RSD-as-a-service/compare/895-extra-organisation-fields?expand=1)). Either you @ctwhome or @dmijatovic would have to make the frontend admin part.
