### ISSUE TITLE
Searching for a Research Unit gives an "Application error"

### ISSUE THREAD

**Issue by tpronk** [research-software-directory/RSD-as-a-service#898]
I created a Research Unit called "Research Data Management" under my organization "Amsterdam University Medical Centers". If I search for this Research Unit on the front page, it takes me to https://research-software-directory.org/organisations/research-data-management, but this page reports "Application error: a client-side exception has occurred (see the browser console for more information)."

**Comment by ewan-escience** [comment]
This is a bug: the error is because the generated URL is wrong, the parent slugs are namely missing (it should be https://research-software-directory.org/organisations/amsterdam-university-medical-centers/research-data-management).

@dmijatovic I though research units were excluded from all searches?

**Comment by dmijatovic** [comment]
This is the bug indeed. We can remove research units from search entries **OR** ensure the url/link is correct.
