### ISSUE TITLE
Upgrade to PostgreSQL 15

### ISSUE THREAD

**Issue by fembau** [research-software-directory/RSD-as-a-service#943]
Are there any plans to upgrade PostgreSQL from 14 to 15?
I want to have [unique constraints](https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS) on tables to treat NULL values as not distinct, p.ex.:
```
CREATE TABLE products (
    product_no integer,
    name text,
    price numeric,
    UNIQUE NULLS NOT DISTINCT (product_no)
);
```

See also this [workaround](https://stackoverflow.com/questions/8289100/create-unique-constraint-with-null-columns/8289253#8289253) using constraints on index.

**Comment by ewan-escience** [comment]
We will look if we can do that this summer, before the upgrade to V2. Note that upgrading a major version requires manual intervention, which is for us a bit more complicated, since we run Postgres from Docker. See also https://www.postgresql.org/docs/current/upgrading.html and e.g. https://www.cloudytuts.com/tutorials/docker/how-to-upgrade-postgresql-in-docker-and-kubernetes/ or https://betterprogramming.pub/how-to-upgrade-your-postgresql-version-using-docker-d1e81dbbbdf9.
